import json
import logging
from typing import Any, Dict, Optional
import redis.asyncio as redis

from app.config import settings

logger = logging.getLogger(__name__)

class RedisManager:
    """Manages async connection to Redis for the two-speed architecture."""
    def __init__(self):
        self.redis_url = settings.redis_url
        self.client: Optional[redis.Redis] = None
        self.MACRO_STATE_KEY = "macro_state:latest"

    async def connect(self):
        if self.client is None:
            try:
                self.client = redis.from_url(self.redis_url, decode_responses=True)
                # Test connection
                await self.client.ping()
                logger.info(f"Successfully connected to Redis at {self.redis_url}")
            except Exception as e:
                logger.error(f"Failed to connect to Redis: {e}")
                self.client = None

    async def disconnect(self):
        if self.client:
            await self.client.close()
            self.client = None
            logger.info("Disconnected from Redis")

    async def set_macro_state(self, state: Dict[str, Any]) -> bool:
        """Saves the latest macro state generated by the Slow LangGraph loop."""
        if not self.client:
            await self.connect()
        
        if not self.client:
             logger.warning("Redis client uninitialized. Cannot set macro state.")
             return False
             
        try:
            state_json = json.dumps(state)
            await self.client.set(self.MACRO_STATE_KEY, state_json)
            return True
        except Exception as e:
            logger.error(f"Error saving macro state to Redis: {e}")
            return False

    async def get_macro_state(self) -> Optional[Dict[str, Any]]:
        """Retrieves the latest macro state for the Fast RL loop."""
        if not self.client:
            await self.connect()
            
        if not self.client:
             logger.warning("Redis client uninitialized. Cannot get macro state.")
             return None
             
        try:
            state_json = await self.client.get(self.MACRO_STATE_KEY)
            if state_json:
                return json.loads(state_json)
            return None
        except Exception as e:
            logger.error(f"Error reading macro state from Redis: {e}")
            return None


# Global singleton instance
redis_manager = RedisManager()
